export type RootStackParamList = {
  Introduce: undefined;
  Login: undefined;
  Character: undefined;
  Story: undefined;
  MyPage: undefined;
  Inquiry: undefined;
  InquiryDetail: { id: number };
  SubmitInquiry: undefined;
  Setting: undefined;
  FAQ: undefined;
  Alarm: undefined;
  Main: undefined;
  Diary: undefined;
  MailBox: undefined;
  WriteDiary: { selectedDate?: string };
  SelectEmotion: undefined;
  CheckDiary: { diaryId: number };
  CheckLetter: { letterId: number };
  Test: undefined;
  EditDiary: { diaryId: number };
  signup: undefined;
  privacy: undefined;
};
